name: Code Checks

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        yarn install

    - name: Typecheck
      run: yarn typecheck
    - name: Lint
      run: yarn lint

    - name: Stylelint
      run: yarn stylelint
  